# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

GET http://localhost:8080/[Name]BookstoreTransact/api/categories
Accept: application/json

###
# curl 'http://localhost:8080/SadathBookstoreTransact/api/orders'
#  -H 'Accept: */*'
#  -H 'Accept-Language: en-US,en;q=0.9'
#  -H 'Cache-Control: max-age=0'
#  -H 'Connection: keep-alive'
#  -H 'Content-Type: application/json'
#  -H 'Origin: http://localhost:5173'
#  -H 'Referer: http://localhost:5173/'
#  -H 'Sec-Fetch-Dest: empty'
#  -H 'Sec-Fetch-Mode: cors'
#  -H 'Sec-Fetch-Site: same-site'
#  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0'
#  -H 'sec-ch-ua: "Microsoft Edge";v="119", "Chromium";v="119", "Not?A_Brand";v="24"'
#  -H 'sec-ch-ua-mobile: ?0'
#  -H 'sec-ch-ua-platform: "Windows"'
#  --data-raw '{"cart":{"itemArray":[{"book":{"bookId":1002,"title":"Fairy Tale","author":"Stephen King","description":"","price":799,"rating":0,"isPublic":false,"isFeatured":false,"categoryId":1001},"quantity":1},{"book":{"bookId":1003,"title":"Dune","author":"Frank Herbert","description":"","price":599,"rating":0,"isPublic":true,"isFeatured":false,"categoryId":1001},"quantity":1},{"book":{"bookId":1004,"title":"Caraval","author":"Stephanie Garber","description":"","price":899,"rating":0,"isPublic":true,"isFeatured":false,"categoryId":1001},"quantity":3}]},"customerForm":{"name":"Sadath Ullah Khan Mohammed","address":"110 Northview Dr","phone":"2407969412","email":"sadathkhn4@gmail.com","ccNumber":"4444333322221111","ccExpiryMonth":11,"ccExpiryYear":2023}}'
#  --compressed
POST http://localhost:8080/SadathBookstoreTransact/api/orders
Accept: */*
Accept-Language: en-US,en;q=0.9
Cache-Control: max-age=0
Connection: keep-alive
Origin: http://localhost:5173
Referer: http://localhost:5173/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0
sec-ch-ua: "Microsoft Edge";v="119", "Chromium";v="119", "Not?A_Brand";v="24"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
Content-Type: application/json

{
  "cart": {
    "itemArray": [
      {
        "book": {
          "bookId": 1002,
          "title": "Fairy Tale",
          "author": "Stephen King",
          "description": "",
          "price": 799,
          "rating": 0,
          "isPublic": false,
          "isFeatured": false,
          "categoryId": 1001
        },
        "quantity": 1
      },
      {
        "book": {
          "bookId": 1003,
          "title": "Dune",
          "author": "Frank Herbert",
          "description": "",
          "price": 599,
          "rating": 0,
          "isPublic": true,
          "isFeatured": false,
          "categoryId": 1001
        },
        "quantity": 1
      },
      {
        "book": {
          "bookId": 1004,
          "title": "Caraval",
          "author": "Stephanie Garber",
          "description": "",
          "price": 899,
          "rating": 0,
          "isPublic": true,
          "isFeatured": false,
          "categoryId": 1001
        },
        "quantity": 3
      }
    ]
  },
  "customerForm": {
    "email": "monica@email.com", "address": "123 Main St", "phone": "408 555 1212", "ccNumber": "4444333322221111", "ccExpiryMonth": 7, "ccExpiryYear": 2026
  }
}

###



